apiVersion: v2
publisher: ms-toolsai 
name: jupyter
version: latest
type: VS Code extension
displayName: Jupyter
title: Jupyter
description: This extension helps in exploring Jupyter extension
icon: https://www-03.ibm.com/press/us/en/attachment/20190.wss?fileId=ATTACH_FILE
repository: https://github.com/Microsoft/vscode-jupyter
category: Programming Languages
firstPublicationDate: '2019-09-19'
spec:
 extensions:
  - "https://github.com/nupurnegi/jupyter_plugin/blob/main/ms-toolsai.jupyter-2021.4.641214696.vsix"
